<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDggd5kw\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDggd5kw/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerDggd5kw.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerDggd5kw\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerDggd5kw\appProdProjectContainer(array(
    'container.build_hash' => 'Dggd5kw',
    'container.build_id' => '2ec895f9',
    'container.build_time' => 1534544493,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerDggd5kw');
